networks:
  shared-network:
    external: true
services:
  web:
    build: .
    container_name: "frontend-api"
    ports:
      - 8080:80
    volumes:
      - ./html:/usr/share/nginx/html
    networks:
      - shared-network
